remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
title: League of Legends Position Analysis
description: by Hannah Gonzalez (hagonzalez@ucsd.edu) and Connie Liu (col024@ucsd.edu)

